---
# Install Nginx & web app

- name: nginx-apt
  apt: pkg=$item state=installed
  with_items:
    - bash
    - nginx

# Directories & files

- name: nginx-user
  user: name=www-data state=present home=/srv/www

- name: nginx-rm-default:
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: /srv/www
  file: path=/srv/www state=directory owner=www-data group=www-data
        
- name: /etc/nginx/sites-available
  file: path=/etc/nginx/sites-available state=directory owner=root mode=0755

- name: /etc/nginx/sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory owner=root mode=0755

# Configure

- name: nginx-config
  copy: src=nginx.conf /etc/nginx/nginx.conf
  notify:
    - restart nginx
 

- include: uwsgi.yml tags=uwsgi
- include: app_bookkeeping.yml tags=app
